ME-41: adjust device decommissioning workflow to the related code change
mendersoftware/workflows pull request #256
Opened 2022-12-14 16:12 UTC by 0lmi

Changelog: None
Ticket: ME-41
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

2022-12-14 16:42 UTC, kjaskiewiczz requested changes

2022-12-15 09:22 UTC, kjaskiewiczz approved these changes
looks good

2022-12-20 06:32 UTC, 0lmi commented
https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/727179103
```
./extra/release_tool.py -b master --pr deviceauth/622 --pr workflows/256 --pr integration/2278
-> DP
-> DC
-> yes
```

2022-12-20 08:30 UTC, tranchitella approved these changes

2022-12-20 08:31 UTC, merged